### PR TITLE
Add an option to disable the disconnect part of the protocol

### PR DESCRIPTION
**Pull request by reda-alaoui**
Fix for #190

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Thank you

**Comment by elakito** [comment]
I find the name of this parameter somewhat too long and confusing.
Can we rename it to simply enableDisconnect or disableDisconnect with the appropriate default setting?

**Comment by jfarcand** [comment]
+1

**Comment by elakito** [comment]
OK. I'll rename it to disableDisconnect because that sounds more intuitive than other options.

**Pull request merged**
